name:                hakyll-dhall
version:             0.2.1.2
github:              "mstksg/hakyll-dhall"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"
tested-with:         GHC >= 8.2 && < 8.8

extra-source-files:
- README.md
- CHANGELOG.md
- test-dhall/*

# Metadata used when publishing your package
synopsis:            Dhall compiler for Hakyll
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mstksg/hakyll-dhall#readme>

ghc-options:
- -Wall
- -Wcompat
- -Wredundant-constraints

dependencies:
- base >= 4.7 && < 5
- dhall > 1.17
- hakyll >= 4.10

library:
  source-dirs: src
  dependencies:
  - binary
  - cborg
  - containers
  - data-default-class
  - filepath
  - lens-family-core
  - mtl
  - prettyprinter
  - text
  - transformers

executables:
  hakyll-dhall-test-app:
    main:                test-app.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hakyll-dhall
