name:                hakyll-dhall
version:             0.1.0.0
github:              "mstksg/hakyll-dhall"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mstksg/hakyll-dhall#readme>

ghc-options:
- -Wall

dependencies:
- base >= 4.7 && < 5
- data-default-class
- dhall > 1.17
- hakyll

library:
  source-dirs: src
  dependencies:
  - binary
  - cborg
  - containers
  - exceptions
  - filepath
  - microlens
  - mtl
  - prettyprinter
  - prettyprinter-ansi-terminal
  - text
  - transformers

executables:
  hakyll-dhall-test-app:
    main:                test-app.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hakyll-dhall

# tests:
#   hakyll-dhall-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - hakyll-dhall
